Added scanners

diff --git a/bin/scuep b/bin/scuep
--- a/bin/scuep
+++ b/bin/scuep
@@ -3,6 +3,13 @@
 state="/home/$USER/.config/scuep"; 
 mkdir -p $state;
 
+cd "$(dirname "$0")";
+
+if [ ! -f ./cue_url_parse ]; then
+	echo "Could not find ./cue_url_parse, did you make it?"
+	exit 1;
+fi
+
 if [ ! -f $1 ]; then
 	mkfifo $state/pipe;
 fi
